{
# 公众号配置
# 公众号appId
"app_id": "wx572d3969505196d6",
# 公众号appSecret
"app_secret": "9d3a096c2bf9700ec0cdd9bcc6d5a680",
# 模板消息id
"template_id":"hKU4LRON8KNBrvXls9JSXxZDhxGdNwnqmIYY0j5nJ2c ",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["oqshN5h23JOYTzu4owYuORqpDWp0"],

# 信息配置
# 和风天气apikey
"weather_key": "46511d6aa2e04abbb786f37c79773ecb",
# 天行数据apikey
"tian_api": " e3b49cb2901441921431873b4883d263",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦(国外城市可能获取不到pm2.5，空气质量，今日建议等数据)
"region": "河南省沁阳市",
# 生日
"birthday1": {"name": "小宝", "birthday": "2004-03-12"},
# 在一起的日子，格式同上
"love_date": "2022-07-11",
# 金句中文，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
